title: Your awesome title
subtitle: Your site's subtitle
email: your-email@example.com
footer-text: <a href="https://github.com/BLumia/jekyll-theme-mutter">Mutter</a> theme build with <i class="i i-heart"></i> on <i class="i i-octodex"></i>
footer-copyright: Your Name &copy; Year
description: >- # this means to ignore newlines until "header_pages:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

header_pages:
  - index.md
  - posts.md
  - about.md

# Build settings
theme: jekyll-theme-mutter
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

